server:
    port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5
  serviceUrl:
    defaultZone: http://localhost:8761
